Last loaded image folder: E:/NLP/VAL_LabelImgs/AutoLabelImg/imgs_input
Last loaded image name: aachen_000004_000019_leftImg8bit_1_phi_2.1.png
Last loaded label folder: E:/NLP/VAL_LabelImgs/AutoLabelImg/save_dir
check_ls: null
classes:
- 2
- 5
- 7
conf: 0.5
filter_conf: 0.85
iou: 0.85
model: models/yolov8n.pt
