Last loaded image folder: E:/VAL_ImglabelImg/imgs_input
Last loaded image name: aachen_000004_000019_leftImg8bit_1_phi_1.8.png
Last loaded label folder: E:/VAL_ImglabelImg/out
check_ls: null
classes:
- 2
- 5
- 7
conf: 0.5
filter_conf: 0.85
iou: 0.85
model: models/yolov8n.pt
